---
# file: roles/iptables/tasks/main.yml
- name: install iptables
  yum: name=iptables
  sudo: yes
  tags:
    - iptables

- name: ensure iptables is running
  service: name=iptables state=started
  sudo: yes
  tags:
    - iptables

- name: install sysconfig/iptables
  copy: src=../files/iptables dest=/etc/sysconfig/iptables owner=root group=root mode=600 seuser=system_u serole=object_r setype=system_conf_t selevel=s0
  sudo: yes
  notify:
    - restart iptables
  tags:
    - iptables

