---
#Copyright 2013 Percona LLC / David Busby
# file: roles/iptables/tasks/main.yml
- name: install iptables
  yum: name=iptables
  become: yes
  tags:
    - iptables

- name: ensure iptables is running
  service: name=iptables state=started
  become: yes
  tags:
    - iptables

- name: install sysconfig/iptables
  template: src=../files/iptables.j2 dest=/etc/sysconfig/iptables owner=root group=root mode=600 seuser=system_u serole=object_r setype=system_conf_t selevel=s0
  become: yes
  notify:
    - restart iptables
  tags:
    - iptables

