---
# file: roles/vuln_webapp/tasks/main.yml

#copy: src=../files/iptables dest=/etc/sysconfig/iptables owner=root group=root mode=600 seuser=system_u serole=object_r setype=system_conf_t selevel=s0

- name: install php
  yum: name={{ item }} state=installed
  with_items:
    - php
    - php-mysql
  sudo: yes
  notify:
    - restart httpd
  tags:
    - vuln_webapp

  #system_u:object_r:httpd_sys_rw_content_t:s0
- name: vulnerable webapp dir
  file: dest=/var/www/html/vuln_webapp owner=apache group=apache mode=777 seuser=system_u serole=object_r setype=httpd_sys_rw_content_t selevel=s0 state=directory
  sudo: yes
  tags:
    - vuln_webapp

- name: vulnerable webapp php files
  copy: src={{ item }} dest=/var/www/html/vuln_webapp owner=apache group=apache mode=777 seuser=system_u serole=object_r setype=httpd_sys_rw_content_t selevel=s0
  with_fileglob:
          - ../files/*.php
  sudo: yes
  tags:
    - vuln_webapp

- name: install MySQL-python
  yum: name=MySQL-python
  sudo: yes
  tags:
    - vuln_webapp
  
- name: deploy really bad grant
  mysql_user: name=vuln_webapp password=pluk priv=*.*:ALL state=present
  tags:
    - vuln_webapp

- name: create vuln_webapp schema
  mysql_db: state=present name=vuln_webapp

- name: deploy vuln_webapp schema
  mysql_db: state=import name=vuln_webapp target=../files/schema.sql
  tags:
    - vuln_webapp
