# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "CentOS6_x64"
  config.vm.box_url = "http://oneiroi.fedorapeople.org/vagrant/centos_6.4_x64_ansible_puppet_chef.box"
  
  config.vm.define "web1" do |webserver|
    webserver.vm.box = "CentOS6_x64"
      webserver.vm.network :private_network, ip: "172.16.33.2"
      webserver.vm.network "forwarded_port", guest: 80, host: 8001
      webserver.vm.provider :virtualbox do |vb|
          vb.gui = true
          vb.customize ["modifyvm", :id, "--memory", "1024"]
      end
      webserver.vm.provision "ansible" do |ansible|
        #ansible.verbose = "vvv"
        ansible.limit = "web1"
        ansible.extra_vars = { setenforce: "1" }
        ansible.tags  = ["selinux", "httpd", "vuln_webapp", "iptables"] 
        ansible.inventory_path = "provisioning/hosts"
        ansible.playbook = "provisioning/playbook.yml"
      end
  end 
  
  config.vm.define "db1" do |dbserver|
    dbserver.vm.box = "CentOS6_x64"
      dbserver.vm.network :private_network, ip: "172.16.33.3"
      dbserver.vm.provider :virtualbox do |vb|
          vb.gui = true
          vb.customize ["modifyvm", :id, "--memory", "1024"]
      end
      dbserver.vm.provision "ansible" do |ansible|
        #ansible.verbose = "vvv"
        ansible.limit = "db1"
        ansible.extra_vars = { setenforce: "1" }
        ansible.tags  = ["selinux", "mysqld", "iptables", "vuln_webapp_mysql"] 
        ansible.inventory_path = "provisioning/hosts"
        ansible.playbook = "provisioning/playbook.yml"
      end
  end 
end
