---
#Copyright 2013 Percona LLC / David Busby
# file: roles/selinux/tasks/main.yml

- name: install libselinux-python
  yum: name=libselinux-python
  become: yes
  tags:
    - selinux

- name: install audit 
  yum: name=audit
  become: yes
  tags:
    - selinux

- name: install dbus
  yum: name=dbus
  become: yes
  tags:
    - selinux

- name: ensure messagebus is running
  service: name=messagebus state=started
  become: yes
  tags:
    - selinux

- name: ensure auditd is running
  service: name=auditd state=started
  become: yes
  tags:
    - selinux

      #- name: install setroubleshoot-server
      #yum: name=setroubleshoot-server
      #become: yes
      #tags:
      #- selinux
      #notify:
      #- restart auditd

- name: setenforce
  command: setenforce {{ setenforce }}
  become: yes
  tags:
    - selinux

