---
# file: roles/selinux/tasks/main.yml

- name: install libselinux-python
  yum: name=libselinux-python
  sudo: yes
  tags:
    - selinux

- name: install audit 
  yum: name=audit
  sudo: yes
  tags:
    - selinux

- name: install dbus
  yum: name=dbus
  sudo: yes
  tags:
    - selinux

- name: ensure messagebus is running
  service: name=messagebus state=started
  sudo: yes
  tags:
    - selinux

- name: ensure auditd is running
  service: name=auditd state=started
  sudo: yes
  tags:
    - selinux

- name: install setroubleshoot-server
  yum: name=setroubleshoot-server
  sudo: yes
  tags:
    - selinux
  notify:
    - restart auditd
