---
#Copyright 2013 Percona LLC / David Busby
# file: roles/httpd/tasks/main.yml

- name: install httpd
  yum: name=httpd
  sudo: yes
  tags:
    - httpd

- name: ensure apache is running
  service: name=httpd state=started
  sudo: yes
  tags:
    - httpd

