---
#Copyright 2013 Percona LLC / David Busby
# file: roles/mysqld/tasks/main.yml

- name: install mysql-server
  yum: name=mysql-server
  become: yes
  tags:
    - mysqld

- name: ensure mysqld is running
  service: name=mysqld state=started
  become: yes
  tags:
    - mysqld

- name: install mysql
  become: yes
  yum: name=mysql
  tags:
    - mysqld
